---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: right-lyrics
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lyrics-page
spec:
  hosts:
    - "*"
  gateways:
    - right-lyrics
  http:
    - route:
        - destination:
            host: lyrics-page
            port:
              number: 8080