---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: musik-gateway
  namespace: musik
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: musik
spec:
  hosts:
  - "*"
  gateways:
  - musik-gateway
  http:
  - route:
    - destination:
        host: page
        port:
          number: 5000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: musik
  namespace: istio-system
spec:
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100          