{{ if .Values.createService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.serviceName }}
{{ end }}