---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    istio-injection: enabled
---
apiVersion: mimik.veicot.io/v1alpha1
kind: Mimik
metadata:
  name: hello-world-frontend-v1
  namespace: hello-world
spec:
  service: hello-world-frontend
  version: v1
  endpoints:
    - path: /
      method: GET
      connections:
        - service: hello-world-backend
          port: 8080
          path: hello
          method: GET
---      
apiVersion: mimik.veicot.io/v1alpha1
kind: Mimik
metadata:
  name: hello-world-backend-v1
  namespace: hello-world
spec:
  service: hello-world-backend
  version: v1
  endpoints:
    - path: /hello
      method: GET
      connections: []  
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-world
  namespace: hello-world
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: hello-world
spec:
  hosts:
    - "*"
  gateways:
    - hello-world
  http:
    - route:
        - destination:
            host: hello-world-frontend
            port:
              number: 8080       