# permissions for end users to view mimiks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mimik-viewer-role
rules:
- apiGroups:
  - mimik.veicot.io
  resources:
  - mimiks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mimik.veicot.io
  resources:
  - mimiks/status
  verbs:
  - get
